Update workflow.yaml

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -8,7 +8,7 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
-      - name: Setup JDK
+      - name: Setup JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
@@ -16,12 +16,15 @@ jobs:
       - name: Setup Flutter
         uses: subosito/flutter-action@v2
         with:
-          flutter-version: '3.24.0'
+          flutter-version: '3.35.2'
           channel: 'stable'
       - name: Extract ZIP
         run: |
           unzip -o flutter-project.zip -d .
-          chmod +x android/gradlew
+          if [ ! -f "pubspec.yaml" ]; then
+            echo "Error: pubspec.yaml tidak ditemukan"
+            exit 1
+          fi
       - name: Install Dependencies
         run: flutter pub get
       - name: Build APK
